# Generated by Django 3.1.3 on 2023-04-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_company_employee_role_rename_team_name_team_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
