# Generated by Django 4.1.7 on 2023-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_customuser_company_id_customuser_role_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission_scope',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
