# Generated by Django 4.1.7 on 2023-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_customuser_is_admin_customuser_username_team_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.CharField(default='0x00000000', max_length=100),
        ),
    ]
