# Generated by Django 3.1.3 on 2023-03-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(blank=True, default='New Team', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(blank=True, max_length=200, null=True)),
                ('f_name', models.CharField(blank=True, max_length=200, null=True)),
                ('l_name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
